[package]
name = "lolfetch"
version = "0.1.0"
edition = "2021"

[dependencies]
riven = "2.56.0"
reqwest = "0.12.5"
tokio = { version = "1.39.2", features = ["full"] }
clap = "4.5.13"
dotenv = "0.15.0"
anyhow = "1.0.86"